# Generated by Django 2.2.7 on 2019-12-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='member',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='faccount',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='member',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='refunds',
            old_name='buyer',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='buyer',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='default_addr',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='buyer_optional_addr',
            name='optional_addr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='billing_addr',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='addr',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('account', 'faccount')},
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('account', 'name')},
        ),
    ]
