# Generated by Django 2.2.7 on 2019-12-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_auto_20191206_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer_optional_addr',
            old_name='buyer',
            new_name='account',
        ),
        migrations.AlterUniqueTogether(
            name='buyer_optional_addr',
            unique_together={('account', 'optional_addr')},
        ),
    ]
