# Generated by Django 2.2.7 on 2019-12-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_auto_20191208_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='card_expr_date',
            field=models.DateField(default='2019-01-01'),
        ),
    ]
