# Generated by Django 2.2.7 on 2019-12-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_auto_20191208_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_picture',
            name='image',
            field=models.ImageField(null=True, upload_to='img/category'),
        ),
    ]
