# Generated by Django 2.2.7 on 2019-12-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_auto_20191208_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistof',
            name='account_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_picture',
            name='image',
            field=models.ImageField(null=True, upload_to='D:/University/3rd Year/DB/Ass/ass2/amazon/template/img/category'),
        ),
    ]
