# Generated by Django 2.2.7 on 2019-12-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_auto_20191210_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='consistof',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
