# Generated by Django 2.2.7 on 2019-12-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_consistof_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='card',
            new_name='card_num',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_expr_date',
            field=models.DateField(default='2019-01-01'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
